# ROOT 아이템
-- ID, NAME 출력
-- ORDER BY ASC;

SELECT I.ITEM_ID, ITEM_NAME
FROM ITEM_INFO AS I
JOIN ITEM_TREE AS T
ON I.ITEM_ID = T.ITEM_ID
WHERE I.ITEM_ID IN
(SELECT ITEM_ID
FROM ITEM_TREE
WHERE PARENT_ITEM_ID IS NULL)
ORDER BY ITEM_ID ASC
;