-- 0시부터 23시까지, 각 시간대별로 입양이 몇 건이나 발생했는지
# 시간대 순 정렬(0시, 1시 - 23시

WITH RECURSIVE ALLHOUR AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1
    FROM ALLHOUR
    WHERE HOUR < 23
)

SELECT A.HOUR, COALESCE(O.COUNT,0) AS COUNT
FROM ALLHOUR AS A
LEFT JOIN 
(
SELECT HOUR(DATETIME) AS HOURS, COUNT(DISTINCT ANIMAL_ID) AS COUNT
FROM ANIMAL_OUTS
GROUP BY HOUR(DATETIME)
) AS O
ON A.HOUR = O.HOURS
ORDER BY HOUR
;


