# 출력 : 3세대 ID
# ORDER BY ID ASC;

# PARENT ID 가 NULL 인 ID 1, ID 2가 1 세대
# ID 1에서 분화된 ID 3, ID 2에서 분화된 ID 4, ID 5 가 2 세대입니다.
# ID 4 에서 분화된 ID 6, ID 3에서 분화된 ID 7 이 3 세대
# ID 6에서 분화된 ID 8은 4 세대.


WITH RECURSIVE GEN_TABLE AS
(
SELECT ID, PARENT_ID,
    1 AS GENERATION
FROM ECOLI_DATA
WHERE PARENT_ID IS NULL
    
UNION ALL

SELECT SECOND.ID, SECOND.PARENT_ID,
    GEN_TABLE.GENERATION +1 AS GENERATION
FROM ECOLI_DATA AS SECOND
INNER JOIN GEN_TABLE
ON GEN_TABLE.ID = SECOND.PARENT_ID
)

SELECT ID
FROM GEN_TABLE
WHERE GENERATION=3
ORDER BY ID ASC