-- FISH_INFO
# ID : 고기의 ID (INT)
# FISH_TYPE : 물고기의 종류(숫자) (INT)
# LENGTH : 잡은 물고기의 길이(cm) (FLOAT) (NULL)
-- LENGTH <= 10 : NULL
# TIME : 물고기를 잡은 날짜 (DATE)

-- FISH_NAME_INFO
# FISH_TYPE : 물고기의 종류(INT)
# FISH_NAME : 물고기의 이름(VAR)


-- 잡은 BASS와 SNAPPER의 수를 출력
-- FISH_COUNT

SELECT COUNT(*) AS FISH_COUNT
FROM FISH_INFO AS FISH
LEFT JOIN FISH_NAME_INFO AS NAME
ON FISH.FISH_TYPE = NAME.FISH_TYPE
WHERE (FISH_NAME = 'BASS') OR (FISH_NAME = 'SNAPPER')
;
