-- CAR_RENTAL_COMPANY_RENTAL_HISTORY 
# HISTORY_ID
# CAR_ID
# START_DATE
# END_DATE

# 2022년 8월 ~ 2022년 10월까지 ( 2022-08-01 ~ 2022-10-31)
# 총 대여횟수가 5회 이상인 자동차
# ----------------------------
# 해당 기간동안의 월별 자동차 ID별 총 대여 횟수
# ORDER BY MONTH ASC, CAR_ID DESC ;


# -- 해당 기간 동안 총 대여횟수가 5회 이상인 자동차 : CAR_ID, RECORDS
WITH RENT_TABLE AS
(
SELECT 
    CAR_ID
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE
    START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY
    CAR_ID
HAVING
    COUNT(*) >= 5
)

SELECT
    MONTH(START_DATE) AS MONTH, A.CAR_ID, COUNT(*) AS RECORDS
FROM 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY AS A
JOIN 
    RENT_TABLE AS R
    ON A.CAR_ID = R.CAR_ID
WHERE
    START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY 
    MONTH(START_DATE), CAR_ID
ORDER BY 
    MONTH ASC, CAR_ID DESC
    ;
