SELECT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS AS D
INNER JOIN SKILLCODES AS S
ON D.SKILL_CODE & S.CODE = S.CODE
GROUP BY D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
HAVING
    (GROUP_CONCAT(S.NAME) LIKE '%Python%') OR (GROUP_CONCAT(S.NAME) LIKE '%C#%')
ORDER BY D.ID
;
