-- CAR_RENTAL_COMPANY_CAR : 대여 중인 자동차들의 정보
# CAR_ID
# CAR_TYPE
# DAILY_FEE
# OPTIONS

-- CAR_RENTAL_COMPANY_RENTAL_HISTORY : 자동차 대여 기록 정보
# HISTORY_ID
# CAR_ID
# START_DATE
# END_DATE

-- CAR_RENTAL_COMPANY_DISCOUNT_PLAN : 자동차 종류 별 대여 기간 종류
# PLAN_ID : 대여기록 ID
# CAR_TYPE
# DURATION_TYPE
# DISCOUNT_RATE (할인율 적용되는 대여 기간은 : 7일 이상(7-30), 30일이상(30-90), 90일 이상(90이상))

# 결과
# 자동차 종류 : 세단 OR SUV - 해결
# 2022년 11월 1일 - 2022년 11월 30일 대여 가능 - 해결
# 30일간의 대여 금액 : 50만 <= X <= 200만 - 해결 
# 자동차 ID, 자동차 종류, 대여금액(FEE)
# ORDER BY FEE DESC, 자동차 종류 ASC, 자동차ID DESC ;

-- FEE_TABLE(세단,SUV,FEE)
# WITH FEE_TABLE AS (
# SELECT A.CAR_ID,A.CAR_TYPE,
# CASE
#     WHEN A.CAR_TYPE = '세단' THEN A.DAILY_FEE*0.9*30
#     WHEN A.CAR_TYPE = 'SUV' THEN A.DAILY_FEE*0.92*30
# END AS FEE
# FROM CAR_RENTAL_COMPANY_CAR AS A
# JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS C
# ON A.CAR_TYPE = C.CAR_TYPE
# WHERE ((A.CAR_TYPE = '세단') OR (A.CAR_TYPE= 'SUV')) AND (DURATION_TYPE = '30일 이상')
# )

    
# -- 11-01, 11-30에 빌릴 수 있는 SUV와 세단 ID
    
# SELECT A.CAR_ID, A.CAR_TYPE, ROUND(F.FEE)
# FROM CAR_RENTAL_COMPANY_CAR AS A
# JOIN 
# (
# SELECT CAR_ID
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE CAR_ID NOT IN 
# (
# SELECT CAR_ID 
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE (START_DATE <= '2022-11-01') AND (END_DATE >= '2022-11-30')
# )
# ) AS B
# ON A.CAR_ID = B.CAR_ID
# JOIN FEE_TABLE AS F
# ON A.CAR_TYPE = F.CAR_TYPE
# WHERE F.FEE >= 500000 AND F.FEE < 2000000
# ORDER BY F.FEE DESC, A.CAR_TYPE ASC, A.CAR_ID DESC ;
-- 내가한거


-- 1. 대여 가능 자동차 식별
WITH Available_Cars AS (
    SELECT DISTINCT A.CAR_ID, A.CAR_TYPE, A.DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR AS A
    LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
    ON A.CAR_ID = H.CAR_ID
    AND (
        (H.START_DATE <= '2022-11-30' AND H.END_DATE >= '2022-11-01')
    )
    WHERE H.CAR_ID IS NULL
    AND (A.CAR_TYPE = '세단' OR A.CAR_TYPE = 'SUV')
),

-- 2. 30일간의 대여 금액 계산
Fee_Table AS (
    SELECT 
        A.CAR_ID,
        A.CAR_TYPE,
        A.DAILY_FEE * 30 * (1 - P.DISCOUNT_RATE / 100) AS FEE
    FROM Available_Cars AS A
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
    ON A.CAR_TYPE = P.CAR_TYPE
    WHERE P.DURATION_TYPE = '30일 이상'
)

-- 3. 대여 금액 필터링 및 정렬
SELECT 
    F.CAR_ID, 
    F.CAR_TYPE, 
    ROUND(F.FEE) AS FEE
FROM Fee_Table AS F
WHERE F.FEE >= 500000 AND F.FEE < 2000000
ORDER BY 
    F.FEE DESC, 
    F.CAR_TYPE ASC, 
    F.CAR_ID DESC;



