# REST_INFO

# 음식종류별
# 즐겨찾기 수가 가장 많은 식당 음식 종류 , ID, 식당 이름, 즐겨찾기 수
# ORDER BY 음식 종류 DESC ;


#1. 음식종류 별 즐겨찾기 수가 가장 많은 식당
WITH TEMP_MAX AS(
SELECT FOOD_TYPE, MAX(FAVORITES) AS `MAX`
FROM REST_INFO 
GROUP BY FOOD_TYPE
)

SELECT R.FOOD_TYPE, R.REST_ID, R.REST_NAME, R.FAVORITES
FROM REST_INFO AS R
JOIN TEMP_MAX AS T
    ON R.FAVORITES = T.MAX
GROUP BY FOOD_TYPE
ORDER BY FOOD_TYPE DESC ;





