-- USED_GOODS_BOARD와 USED_GOODS_FILE 테이블에서
# 조회수가 가장 높은 중고거래 게시물에 대한 첨부파일 경로
# FILE ID 를 기준으로 내림차순
# /HOOME/GREP/SRC/게시글ID/파일ID/파일이름/파일확장자
# BOARDID/FILEID FILE_NAME.FILE_EXT

SELECT CONCAT('/home/grep/src/',B.BOARD_ID,'/',F.FILE_ID,F.FILE_NAME,F.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_BOARD AS B
JOIN USED_GOODS_FILE AS F
ON F.BOARD_ID = B.BOARD_ID
WHERE VIEWS = 
(
SELECT MAX(VIEWS)
FROM USED_GOODS_BOARD
)
ORDER BY F.FILE_ID DESC;
;


