# SIZE_OF_COLONY : 내림차순
# 0-25 : CRITICAL
# 26-50 : HIGH
# 51-75 : MEDIUM
# 76-100 : LOW
# ---------------------------------
# ORDER BY ID ASC;
# 분류된 이름 : COLONY_NAME

SELECT ID, 
CASE
    WHEN PERCENT_RANK() OVER(ORDER BY SIZE_OF_COLONY DESC) <= 0.25 THEN 'CRITICAL'
    WHEN PERCENT_RANK() OVER(ORDER BY SIZE_OF_COLONY DESC) <= 0.5 THEN 'HIGH'
    WHEN PERCENT_RANK() OVER(ORDER BY SIZE_OF_COLONY DESC) <= 0.75 THEN 'MEDIUM'
    ELSE 'LOW'
END AS COLONY_NAME
FROM ECOLI_DATA
ORDER BY ID ASC