-- USED_GOODS_BOARD 
# BOARD_ID : 게시글 ID
# WRITER_ID : 작성자 ID
# TITLE : 게시글 제목
# CONTENTS : 게시글 내용
# PRICE : 가격
# CREATED_DATE : 작성일
# STATUS : 거래상태
# VIEWS : 조회수

-- USED_GOODS_REPLY 
# REPLY_ID : 댓글 ID
# BOARD_ID : 게시글 ID
# WRITER_ID : 작성자 ID
# CONTENTS : 댓글 내용
# CREATED_DATE : 작성일

# 2022년 10월에 작성
# 게시글 제목, ID, 댓글ID , 댓글작성자 ID, 댓글내용, 댓글 작성일
# ORDER BY 댓글 작성일, 게시글 제목 ASC; 

SELECT B.TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, DATE_FORMAT(R.CREATED_DATE, '%Y-%m-%d') as CREATED_DATE
FROM USED_GOODS_BOARD AS B
JOIN USED_GOODS_REPLY AS R
ON B.BOARD_ID = R.BOARD_ID
WHERE (YEAR(B.CREATED_DATE) = 2022) AND (MONTH(B.CREATED_DATE) = 10)
ORDER BY R.CREATED_DATE, B.TITLE ASC
;

