-- 출력
# EMP_NO
# EMP_NAME
# GRADE
# BONUS

WITH GRADE_BONUS AS
(
SELECT 
EG.EMP_NO,
CASE
    WHEN EG.GRADE = 'S' THEN (EG.SAL*0.2)
    WHEN EG.GRADE = 'A' THEN (EG.SAL*0.15)
    WHEN EG.GRADE = 'B' THEN (EG.SAL*0.1)
    ELSE (EG.SAL*0)
    END AS BONUS
,
EG.GRADE
FROM (SELECT E.EMP_NO,
E.SAL,
CASE
    WHEN AVG(G.SCORE) >= 96 THEN 'S'
    WHEN AVG(G.SCORE) >= 90 THEN 'A'
    WHEN AVG(G.SCORE) >= 80 THEN 'B'
    ELSE 'C'
    END AS GRADE
FROM HR_EMPLOYEES AS E
INNER JOIN HR_GRADE AS G
ON G.EMP_NO = E.EMP_NO
GROUP BY EMP_NO
) AS EG
)

SELECT
EE.EMP_NO,
EE.EMP_NAME,
GB.GRADE,
GB.BONUS
FROM HR_EMPLOYEES AS EE
INNER JOIN GRADE_BONUS AS GB
ON EE.EMP_NO = GB.EMP_NO
ORDER BY EMP_NO ASC
;

