# LINE : 호선(VAR)
# NO : 순번 
# ROUTE : 노선(VAR)
# STATION_NAME : 역 이름 (VAR)
# D_BETWEEN_DIST : 역 사이 거리
# D_CUMULATIVE : 노선별 누계 거리

# 노선별
# 노선
# 총 누계거리 : 역 사이 거리(D_BETWEEN_DIST)의 총 합
# 평균 역 사이 거리 : 

SELECT
ROUTE,
CONCAT(ROUND(SUM(D_BETWEEN_DIST),1),'km') AS TOTAL_DISTANCE,
CONCAT(ROUND(AVG(D_BETWEEN_DIST),2),'km') AS AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE
GROUP BY ROUTE
ORDER BY SUM(D_BETWEEN_DIST) DESC
;
