# 고양이와 개가 몇마리인지 조회
# 고양이를 개보다 먼저 조회

SELECT ANIMAL_TYPE, COUNT(*) AS `count`
FROM 
(
SELECT NAME, ANIMAL_TYPE
FROM ANIMAL_INS 
GROUP BY ANIMAL_ID
) AS TEMP
GROUP BY ANIMAL_TYPE
ORDER BY ANIMAL_TYPE ASC
;