-- CAR_RENTAL_COMPANY_RENTAL_HISTORY
# ID
# AVAILABILITY 컬럼
# 2022년 10월 16에 대여 중인 자동차 : 대여중 (반납날이 16일이어도 대여중)
# 대여중이지 않은 자동차            : 대여 가능
# ORDER BY CAR_ID DESC ;

WITH RENT AS (
SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE -- 사이에 10.16이 있어야 값이 나온다 -> 대여중
)

SELECT H.CAR_ID, 
CASE
    WHEN R.CAR_ID IS NOT NULL THEN '대여중'
    ELSE '대여 가능'
    END AS AVAILABILITY
FROM (SELECT DISTINCT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) AS H
LEFT JOIN RENT AS R
ON H.CAR_ID = R.CAR_ID
ORDER BY H.CAR_ID DESC
;























# WITH RENT AS (
#     SELECT CAR_ID
#     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#     WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE
# ) 

# SELECT A.CAR_ID,
#     CASE
#         WHEN B.CAR_ID IS NOT NULL THEN '대여중'
#         ELSE '대여 가능'
#     END AS AVAILABILITY
# FROM (SELECT DISTINCT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) A
# LEFT JOIN RENT B
# ON A.CAR_ID = B.CAR_ID
# ORDER BY CAR_ID DESC
# ;
