# 세대별 자식이 없는 개체 수 (COUNT), 세대(GENERATION)
# ORDER BY GENERATION ASC

WITH RECURSIVE GEN_TABLE AS
(
SELECT ID, PARENT_ID,
    1 AS GENERATION
FROM ECOLI_DATA
WHERE PARENT_ID IS NULL

UNION ALL
    
SELECT SECOND.ID, SECOND.PARENT_ID,
    GEN_TABLE.GENERATION+1 AS GENERATION
FROM ECOLI_DATA AS SECOND
INNER JOIN GEN_TABLE
ON SECOND.PARENT_ID = GEN_TABLE.ID
)

SELECT COUNT(*) AS COUNT, GENERATION
FROM GEN_TABLE
WHERE NOT EXISTS
(
SELECT 1
FROM ECOLI_DATA AS THIRD
WHERE THIRD.PARENT_ID   = GEN_TABLE.ID
)
GROUP BY GEN_TABLE.GENERATION
ORDER BY GEN_TABLE.GENERATION ASC
;