# ONINE_SALE, OFFLINE_SALE


# 2022년 3월 오프라인/온라인 상품 판매 데이터의
# 판매날짜, 상품ID, 유저ID, 판매량

# OFFLINE_SALE 테이블의 판매데이터의 USER_ID값은 NULL로 표시
# ORDER BY 판매일 ASC, 상품 ID ASC, 유저 ID ASC ;
WITH TEMP AS(
SELECT
    SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM
    ONLINE_SALE
WHERE
    SALES_DATE >= '2022-03-01' AND SALES_DATE < '2022-04-01'

UNION ALL

SELECT
    SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
FROM 
    OFFLINE_SALE
WHERE
    SALES_DATE >= '2022-03-01' AND SALES_DATE < '2022-04-01'
)

SELECT
    DATE_FORMAT(SALES_DATE,'%Y-%m-%d') AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM
    TEMP
ORDER BY
    SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC ;
