# MEMBER_PROFILE : MEMBER_ID
# REST_REVIEW : MEMBER_ID

# 테이블에서 리뷰를 가장 많이 작성한 회원의 리뷰들 조회
# 회원 이름, 리뷰 텍스트, 리뷰 작성일 출력
# ORDER BY 리뷰 작성일 ASC, 리뷰 텍스트 ASC;

# MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE


WITH REVIEW_COUNT AS(
SELECT
    MEMBER_ID, COUNT(*) AS REVIEW_COUNT
FROM 
    REST_REVIEW
GROUP BY    
    MEMBER_ID
ORDER BY 
    REVIEW_COUNT DESC
),

MAX_COUNT AS (
SELECT
    *
FROM 
    REVIEW_COUNT
WHERE
    REVIEW_COUNT = 
    (SELECT 
        MAX(REVIEW_COUNT)
    FROM 
        REVIEW_COUNT)
)

SELECT
    M.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM 
    MEMBER_PROFILE AS M
JOIN
    REST_REVIEW AS R
    ON M.MEMBER_ID = R.MEMBER_ID
JOIN
    MAX_COUNT AS `MAX`
    ON `MAX`.MEMBER_ID = M.MEMBER_ID
ORDER BY
    REVIEW_DATE ASC, REVIEW_TEXT ASC ;









