# ID, CHILD_COUNT
# 자식이 없다면 자식의 수는 0 출력
# ORDER BY ID ASC;

SELECT `FIRST`.ID, COUNT(SECOND.ID) AS CHILD_COUNT
FROM ECOLI_DATA AS `FIRST`
LEFT JOIN ECOLI_DATA AS SECOND
ON `FIRST`.ID = SECOND.PARENT_ID
GROUP BY `FIRST`.ID
;
