# 2022년 1월
# SUM(카테고리 별 도서 판매량)

-- 2022년 1월 출판 도서
# WITH TEMP_BOOK AS(
# SELECT
#     BOOK_ID,CATEGORY
# FROM
#     BOOK
# WHERE
#     SALES_DATE >= '2022-01-01' AND SALES_DATE < '2022-02-01'
# )


SELECT
    CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM
    BOOK AS A
JOIN 
    BOOK_SALES AS B
    ON A.BOOK_ID = B.BOOK_ID
WHERE
    SALES_DATE >= '2022-01-01' AND SALES_DATE < '2022-02-01'
GROUP BY
    CATEGORY
ORDER BY
    CATEGORY ASC
;


