# 분화된 연도(YEAR)
# 연도별 대장균 크기의 편차(YEAR_DEV) : 연도별 가장 큰 대장균 크기 - 각 대장균 크기
# ID

WITH TEMP_TABLE AS (
SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
FROM ECOLI_DATA
GROUP BY YEAR(DIFFERENTIATION_DATE)
)

SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR,
        (T.MAX_SIZE - E.SIZE_OF_COLONY) AS YEAR_DEV,
        ID
FROM ECOLI_DATA AS E
INNER JOIN TEMP_TABLE AS T ON
T.YEAR = YEAR(E.DIFFERENTIATION_DATE)
ORDER BY YEAR ASC,
        YEAR_DEV ASC;
