# FOOD_PRODUCT : 식품 정보
# FOOD_ORDER : 식품 주문 정보
# 공통 : PRODUCT_ID

# 생산일자 2022년 5월 
# 식품ID, 식품 이름, 총매출 
# ORDER BY 총매줄 DESC, 식품 ID ASC ;

SELECT
    P.PRODUCT_ID, P.PRODUCT_NAME, 
    (SUM(AMOUNT) * PRICE) AS TOTAL_SALES
FROM 
    FOOD_PRODUCT AS P
JOIN
    FOOD_ORDER AS O
    ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE
    O.PRODUCE_DATE >= '2022-05-01' AND O.PRODUCE_DATE < '2022-06-01'
GROUP BY
    PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC ;
