-- CAR_RENTAL_COMPANY_CAR 테이블과 CAR_RENTAL_COMPANY_RENTAL_HISTORY 테이블에서
# 자동차 종류 : 세단
# 10월에 대여를 시작한 자동차
# ID 중복 x
# ORDER BY CAR_ID DESC ;

SELECT C.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR AS C
JOIN 
(
SELECT CAR_ID, MONTH(START_DATE) AS DATE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE MONTH(START_DATE) = 10
)
AS H
ON C.CAR_ID = H.CAR_ID
WHERE C.CAR_TYPE = '세단'
GROUP BY C.CAR_ID
ORDER BY CAR_ID DESC ;