# CS OR GS인 
# 의사의 이름, 의사ID, 진료과, 고용일자 조회
# ORDER BY 고용일자 DESC, NAME ASC ;

SELECT
    DR_NAME, DR_ID, MCDP_CD, DATE_FORMAT(HIRE_YMD,'%Y-%m-%d') AS HIRE_YMD
FROM 
    DOCTOR
WHERE
    (MCDP_CD = 'CS') OR (MCDP_CD = 'GS')
ORDER BY
    HIRE_YMD DESC, DR_NAME ASC
    ;
