# 2022년도 평가 점수가 가장 높은 사원
# 점수(SCORE), 사번(EMP_NO), 성명(EMP_NAME), 직책(POSITION), 이메일(EMAIL)
# 2022년도의 평가 점수는 상,하반기 점수의 합 : SCORE

WITH MAX_SCORE AS 
(
SELECT
EMP_NO,
SUM(SCORE) AS MAX_SCORE
FROM HR_GRADE
WHERE YEAR = 2022
GROUP BY EMP_NO
)

SELECT M.MAX_SCORE AS SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_EMPLOYEES AS E
INNER JOIN MAX_SCORE AS M
ON E.EMP_NO = M.EMP_NO
ORDER BY MAX_SCORE DESC
LIMIT 1
;