# MEMBER_PROFILE 
# 생일 3월, 
# 여성 회원 ID, 이름, 성별, 생년월일 
# 전화번호 NULL인 경우 제외
# ORDER BY 회원 ID ASC ;

SELECT
    MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH,'%Y-%m-%d') AS DATE_OF_BIRTH
FROM
    MEMBER_PROFILE
WHERE
    TLNO IS NOT NULL
    AND
    GENDER = 'W'
    AND
    MONTH(DATE_OF_BIRTH) = 3
ORDER BY 
    MEMBER_ID ASC ;
    
    
    
# SELECT
#     MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH,'%Y-%m-%d') AS DATE_OF_BIRTH
# FROM
#     MEMBER_PROFILE
# WHERE
#     TLNO IS NOT NULL
#     AND
#     GENDER = 'W'
#     AND
#     MONTH(DATE_OF_BIRTH) = 3
# ORDER BY 
#     MEMBER_ID ASC ;
