# MEAN(LENGTH) >= 33 물고기를 종류별 분류
# 잡은수(COUNT), 최대길이(MAX(LENGTH)), 종류(FISH_TYPE)
# 물고기 종류 오름차순
# 10CM 이하 물고기들은 10CM로 취급


SELECT 
COUNT(*) AS FISH_COUNT,
MAX(LENGTH) AS MAX_LENGTH,
FISH_TYPE
FROM FISH_INFO
GROUP BY FISH_TYPE
HAVING
    AVG(COALESCE(LENGTH,10)) >= 33
ORDER BY FISH_TYPE;